image_size: 32
num_classes: 10
in_channels: 3
batch_size: 32
start_lr: 0.001
epochs: 300
early_stopping: True
early_stopping_patience: 10
auto_augment: True
rand_augment: True
num_workers: 4
optimizer: "Adam"
optimizer_args: {}
lr_scheduler: 'plateau'
lr_scheduler_args: {'patience': 3}
