image_size: 32
num_classes: 10
in_channels: 3
batch_size: 256
start_lr: 0.01
epochs: 100
early_stopping: False
early_stopping_patience: 10
auto_augment: True
rand_augment: True
num_workers: 4
optimizer: "SGD"
optimizer_params: {'momentum': 0.9, "weight_decay": 0.0001}
lr_scheduler: 'cosine'
lr_scheduler_params: {'T_0': 100}
