image_size: 28
num_classes: 10
in_channels: 3
batch_size: 128
start_lr: 0.001
epochs: 300
early_stopping: True
early_stopping_patience: 10
num_workers: 4
optimizer: "Adam"
optimizer_args: {}
lr_scheduler: 'step'