image_size: [1600, 900]
num_classes: 1000
in_channels: 3
batch_size: 512
start_lr: 0.2
epochs: 120
auto_augment: True
rand_augment: True
early_stopping: False
early_stopping_patience: 5
num_workers: 4
optimizer: "SGD"
optimizer_params: {'momentum': 0.9, "weight_decay": 0.0001}
last_lr_scheduler: 'step'
train_res: 224
val_res: 224
