image_size: 224
batch_size: 32
in_channels: 3
start_lr: 0.01
epochs: 300
early_stopping: False
early_stopping_patience: 10
auto_augment: False
rand_augment: False
num_workers: 4
optimizer: "SGD"
optimizer_params: {'momentum': 0.9, "weight_decay": 0.0001}
lr_scheduler: 'plateau'
lr_scheduler_args: {'patience': 10}
seg_heads_loss_weight: 0.2